### ISSUE TITLE
Convert Line segments to Graph

### ISSUE THREAD

**Issue by mohammedX6** [moovida/dart_jts#13]
How I can convert a list of Line segments to a Graph?

**Comment by mohammedX6** [comment]
@moovida it could be changeling, but I will give it a try.

**Comment by mohammedX6** [comment]
@moovida I[ ported this implementation of the A* algorithm](https://www.codeproject.com/Articles/1221034/Pathfinding-Algorithms-in-Csharp) from C# earlier but it gave me wrong results, maybe I missed something I don't know ...

**Comment by moovida** [comment]
@mohammedX6 , a pity the A* didn't work out. That was a really cool one.

No, JTS doesn't implement that. Everything on top of that is in the geotools library. And Dijkstra is implemented in that graph module of geotools. Geotools uses jts under the hood, so when it comes to coordinates and geometries, it is compatible. That is the main reason I proposed it. And since it has testcases, if for some reason the port doesn't work, you are able to debug both languages and see where the problem lies. 
But yes, it sure is a bit of work.

**Comment by mohammedX6** [comment]
Thanks @moovida
